# Generate the go struct command: sponge config --server-dir=./serverDir
# App config from nacos

# nacos settings
nacos:
  ipAddr: "192.168.3.37"    # server address
  port: 8848                      # listening port
  scheme: "http"               # http or grpc
  contextPath: "/nacos"     # path
  namespaceID: "3454d2b5-2455-4d0e-bf6d-e033b086bb4c" # namespace id
  group: "dev"                    # group name: dev, prod, test
  dataID: "serverNameExample.yml"  # config file id
  format: "yaml"                 # configuration file type: json,yaml,toml
